PRODUCT_IMG_LOCATION: file:D:/ProductSelection/
PRODUCT_IMG_UPLOAD: D:/ProductSelection/
server:
  port: 9999
spring:
  datasource:
    url: jdbc:sqlserver://192.168.1.99:2433;DatabaseName=kyokutoh_test
    username: sidee
    password: sidee2018
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 1234