PRODUCT_IMG_LOCATION: file:D:/ProductSelection/
PRODUCT_IMG_UPLOAD: D:/ProductSelection/
server:
  port: 8888
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=kyokutoh
    username: sa
    password: JDong@2018
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 1234