PRODUCT_IMG_LOCATION: file:D:/ProductSelection/
PRODUCT_IMG_UPLOAD: D:/ProductSelection/
server:
  port: 8888
spring:
  datasource:
    url: jdbc:sqlserver://192.168.1.206:1433;DatabaseName=kyokutoh
    username: sa
    password: centos7.3
  rabbitmq:
    host: 192.168.1.206
    port: 5672
    username: admin
    password: 1234
